package com.embio.tht.beans;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * AccountInfo generated by hbm2java
 */
public class AccountInfo implements java.io.Serializable {

	private Integer id;
	private String status;
	private String accountName;
	private String password;
	private Integer isLoggedIn;
	
	public AccountInfo() {
	}

	public AccountInfo(int id) {
		this.id = id;
	}

	public AccountInfo(int id, Integer userId, String status,
			int roleId, String accountName, String password) {
		this.id = id;
		this.status = status;
		this.accountName = accountName;
		this.password = password;
	}
	public Integer getIsLoggedIn() {
		return this.isLoggedIn;
	}

	public void setIsLoggedIn(Integer isLoggedIn) {
		this.isLoggedIn = isLoggedIn;
	}
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
