package com.embio.tht.beans;
// Generated Apr 17, 2015 8:20:08 PM by Hibernate Tools 3.4.0.CR1


/**
 * Authorities generated by hbm2java
 */
public class Authorities implements java.io.Serializable {

	private Integer id;
	private String username;
	private String authority;

	public Authorities() {
	}

	public Authorities(Integer id) {
		this.id = id;
	}

	public Authorities(Integer id, String username, String authority) {
		this.id = id;
		this.username = username;
		this.authority = authority;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
