package com.embio.tht.beans;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Cards generated by hbm2java
 */
public class Cards implements java.io.Serializable {

	private Integer id;
	private String cardId;
	private String expireDate;

	public Cards() {
	}

	public Cards(int id) {
		this.id = id;
	}

	public Cards(int id, String cardId, String expireDate) {
		this.id = id;
		this.cardId = cardId;
		this.expireDate = expireDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCardId() {
		return this.cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	public String getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(String expireDate) {
		this.expireDate = expireDate;
	}

}
