package com.embio.tht.beans;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * CartItem generated by hbm2java
 */
public class CartItem implements java.io.Serializable {

	private Integer id;
	private Integer restaurantId;

	public CartItem() {
	}

	public CartItem(int id, Integer restaurantId) {
		this.id = id;
		this.restaurantId = restaurantId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}
}
