package com.embio.tht.beans;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * CartItemUnit generated by hbm2java
 */
public class CartItemUnit implements java.io.Serializable {

	private Integer id;
	private Integer dishId;
	private Integer quantity;
	private Integer restaurantId;
	private Integer userInfoId;
	
	private Integer placed;
	public Integer getPlaced(){return this.placed;}
	public void setPlaced(Integer placed){this.placed = placed;}
	
	private Dish dish;
	public Dish getDish(){return this.dish;}
	public void setDish(Dish dish){this.dish = dish;}
	
	private Restaurant restaurant;
	public Restaurant getRestaurant(){return this.restaurant;}
	public void setRestaurant(Restaurant dish){this.restaurant = restaurant;}
	
	private UserInfo userInfo;
	public UserInfo getUserInfo(){return this.userInfo;}
	public void setUserInfo(UserInfo dish){this.userInfo = userInfo;}
	
	public CartItemUnit() {
	}

	public CartItemUnit(int dishId, Integer quantity,
			int restaurantId) {
		this.dishId = dishId;
		this.quantity = quantity;
		this.restaurantId = restaurantId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getDishId() {
		return this.dishId;
	}

	public void setDishId(int dishId) {
		this.dishId = dishId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}
	
	public Integer getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(int userInfoId) {
		this.userInfoId = userInfoId;
	}
}
