package com.embio.tht.beans;

import java.util.ArrayList;
import java.util.List;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1



/**
 * Dish generated by hbm2java
 */
public class Dish implements java.io.Serializable {

	private Integer id;
	private String name;
	private Double price;
	private String image;
	private Integer restaurantId;
	
	private Restaurant restaurant;
	public Restaurant getRestaurant(){return this.restaurant;}
	public void setRestaurant(Restaurant restaurant){this.restaurant = restaurant;}

	private List<DishIngredientItem> ingredients = new ArrayList<DishIngredientItem>();
	public List<DishIngredientItem> getIngredients(){return this.ingredients;}
	public void setIngredients(List<DishIngredientItem> ingredients){this.ingredients = ingredients;}
	
	public Dish() {
	}

	public Dish(int id) {
		this.id = id;
	}

	public Dish(int id, String name, Double price, String image,
			int restaurantId) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.image = image;
		this.restaurantId = restaurantId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}

	public Integer getCalorie(){
		Integer calorie = 0;
		for(DishIngredientItem dii:ingredients){
			calorie += dii.getAmount()*dii.getIngredient().getCalorie();
		}
		return calorie;
	}
}
