package com.embio.tht.beans;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable {

	private Integer id;
	private String name;

	public Location() {
	}

	public Location(int id) {
		this.id = id;
	}

	public Location(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
