package com.embio.tht.beans;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrderInfo generated by hbm2java
 */
public class OrderInfo implements java.io.Serializable {

	private Integer id;
	private Integer customerId;
	private String timeStamp;

	public OrderInfo() {
	}

	public OrderInfo(int id, Integer restaurantId, Integer customerId) {
		this.id = id;
		this.customerId = customerId;
	}

	public OrderInfo(int id, Integer restaurantId, Integer customerId,
			String timeStamp, String comsumeTime) {
		this.id = id;
		this.customerId = customerId;
		this.timeStamp = timeStamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}



	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public String getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(String timeStamp) {
		this.timeStamp = timeStamp;
	}



}
