package com.embio.tht.beans;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1



/**
 * OrderItem generated by hbm2java
 */
public class OrderItem implements java.io.Serializable {

	private Integer id;
	private Integer quantity;
	private Integer orderId;
	private Integer restaurantId;
	private Integer dishId;
	private String consumeTime;

	public OrderItem() {
	}

	public OrderItem(int id) {
		this.id = id;
	}

	public OrderItem(int id, Integer quantity) {
		this.id = id;
		this.quantity = quantity;
	}
	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}
	public Integer getDishId() {
		return this.dishId;
	}

	public void setDishId(int dishId) {
		this.dishId = dishId;
	}
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}
	
	public String getConsumeTime() {
		return this.consumeTime;
	}

	public void setConsumeTime(String consumeTime) {
		this.consumeTime = consumeTime;
	}
}
