package com.embio.tht.beans;

import java.util.Date;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1



/**
 * OrderItem generated by hbm2java
 */
public class OrderItem implements java.io.Serializable {

	private Integer id;
	private Integer quantity;
	private Integer orderInfoId;
	private Integer restaurantId;
	private Integer dishId;
	private String consumeTime;

	private Restaurant restaurant;
	public Restaurant getRestaurant(){return this.restaurant;}
	public void setRestaurant(Restaurant dish){this.restaurant = restaurant;}
	
	private Dish dish;
	public Dish getDish(){return this.dish;}
	public void setDish(Dish dish){this.dish = dish;}
	
	private Ticket ticket;
	public Ticket getTicket(){return this.ticket;}
	public void setTicket(Ticket ticket){this.ticket = ticket;}
	
	private Integer used;
	public Integer getUsed(){return this.used;}
	public void setUsed(Integer used){this.used = used;}
	
	public OrderItem() {
	}

	public OrderItem(int id) {
		this.id = id;
	}

	public OrderItem(int id, Integer quantity) {
		this.id = id;
		this.quantity = quantity;
	}
	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}
	public Integer getDishId() {
		return this.dishId;
	}

	public void setDishId(int dishId) {
		this.dishId = dishId;
	}
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public Integer getOrderInfoId() {
		return this.orderInfoId;
	}

	public void setOrderInfoId(int orderInfoId) {
		this.orderInfoId = orderInfoId;
	}
	
	public String getConsumeTime() {
		return this.consumeTime;
	}

	public void setConsumeTime(String consumeTime) {
		this.consumeTime = consumeTime;
	}
	
	public Integer getComsumedCalorie(){
		if(this.used.equals(1))
			return this.dish.getCalorie()*this.quantity;
		return 0;
	}
	
	public Integer getCalorie(){
		return this.quantity*this.dish.getCalorie();
	}
	
	public Integer getUncomsumedCalorie(){
		if(this.used.equals(0))
			return this.dish.getCalorie()*this.quantity;
		return 0;
	}
	
	public boolean isConsume(){
		return this.used == 0?false:true;
	}
	
	public boolean isConsumedToday(){
		if(this.used.equals(0)) return false;
		
		Date consumeDay = new Date(this.consumeTime);
		Date today = new Date();
		
		if(consumeDay.getYear() == today.getYear() &&
			consumeDay.getMonth() == today.getMonth() &&
			consumeDay.getDate() == today.getDate())
			return true;
		else
			return false;
	}
	
	public Date getConsumeDate(){
		return new Date(this.consumeTime);
	}
}
