package com.embio.tht.beans;

import java.util.ArrayList;
import java.util.List;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * OrderInfo generated by hbm2java
 */
public class OrderInfo implements java.io.Serializable {

	private Integer id;
	private Integer customerId;
	private String timeStamp;

	private List<OrderItem> items = new ArrayList<OrderItem>();
	public List<OrderItem> getItems(){return this.items;}
	public void setItems(List<OrderItem> items){this.items = items;}
	
	private Customer customer;
	public Customer getCustomer(){return this.customer;}
	public void setCustomer(Customer customer){this.customer = customer;}
	
	public OrderInfo() {
	}

	public OrderInfo(int id, Integer restaurantId, Integer customerId) {
		this.id = id;
		this.customerId = customerId;
	}

	public OrderInfo(int id, Integer restaurantId, Integer customerId,
			String timeStamp, String comsumeTime) {
		this.id = id;
		this.customerId = customerId;
		this.timeStamp = timeStamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}



	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public String getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(String timeStamp) {
		this.timeStamp = timeStamp;
	}

	public Integer getComsumedCalorie(){
		int calorie = 0;
		for(OrderItem oi:items){
			calorie += oi.getComsumedCalorie();
		}
		return calorie;
	}
	
	public Integer getUncomsumedCalorie(){
		int calorie = 0;
		for(OrderItem oi:items){
			calorie += oi.getUncomsumedCalorie();
		}
		return calorie;
	}

	public Integer getTodayComsumedCalorie(){
		int calorie = 0;
		for(OrderItem oi:items){
			if(oi.isConsumedToday())
				calorie += oi.getComsumedCalorie();
		}
		return calorie;
	}
}
