package com.embio.tht.beans;
// Generated Apr 7, 2015 4:31:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer locationId;
	private String address;
	private Integer accountId;

	public Restaurant() {
	}

	public Restaurant(int id) {
		this.id = id;
	}

	public Restaurant(int id, String name, Integer locationId,
			String address, Integer accountId) {
		this.id = id;
		this.name = name;
		this.locationId = locationId;
		this.address = address;
		this.accountId = accountId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

}
