package com.embio.tht.beans;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

	private Integer id;
	private String code;
	private String expiredate;
	private Integer orderId;

	public Ticket() {
	}

	public Ticket(int id, Integer orderId) {
		this.id = id;
		this.orderId = orderId;
	}

	public Ticket(int id, String code, String expiredate, Integer orderId) {
		this.id = id;
		this.code = code;
		this.expiredate = expiredate;
		this.orderId = orderId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(String expiredate) {
		this.expiredate = expiredate;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

}
