package com.embio.tht.beans;

import java.util.ArrayList;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1



/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer age;
	private Integer locationId;
	private String gender;
	private String address;
	private Integer accountId;
	
	private Location location;
	public Location getLocation(){return this.location;}
	public void setLocation(Location location){this.location = location;}
//	
//	private ArrayList<CartItemUnit> items = new ArrayList<CartItemUnit>();

	public UserInfo() {
	}

	public UserInfo(Integer id) {
		this.id = id;
	}

	public UserInfo(Integer id, String name, Integer age, Integer locationId,
			String gender, String address) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.locationId = locationId;
		this.gender = gender;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	

	
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
