package com.embio.tht.beans;
// Generated Apr 6, 2015 10:54:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * AccountInfo generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private Integer enabled;
	private String userName;
	private String password;
	private Integer isLoggedIn;
	
	public Users() {
	}

	public Users(int id) {
		this.id = id;
	}

	public Integer getIsLoggedIn() {
		return this.isLoggedIn;
	}

	public void setIsLoggedIn(Integer isLoggedIn) {
		this.isLoggedIn = isLoggedIn;
	}
	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
